#!/bin/sh

set -eu

repo_root=$(CDPATH='' cd -- "$(dirname "$0")/.." && pwd)

grep -Eq '^FROM ubuntu:24\.04@sha256:[0-9a-f]{64}$' "$repo_root/Dockerfile"
grep -Eq '^ARG UBUNTU_SNAPSHOT=[0-9]{8}T[0-9]{6}Z$' "$repo_root/Dockerfile"
grep -F 'noble-security main restricted universe multiverse' "$repo_root/Dockerfile" >/dev/null
grep -F 'COPY requirements.${TARGETARCH}.lock /tmp/requirements.lock' "$repo_root/Dockerfile" >/dev/null
grep -F -- '--require-hashes' "$repo_root/Dockerfile" >/dev/null
for arch in amd64 arm64; do
    lock="$repo_root/requirements.${arch}.lock"
    grep -Eq '^checkov==3\.3\.8([[:space:]]|$)' "$lock"
    grep -Eq '^pre-commit==4\.6\.0([[:space:]]|$)' "$lock"
done

# Keep each supported architecture's fully resolved dependency graph separate.
grep -F 'autogenerated by pip-compile with Python 3.12' "$repo_root/requirements.amd64.lock" >/dev/null
grep -F 'autogenerated by pip-compile with Python 3.12' "$repo_root/requirements.arm64.lock" >/dev/null

grep -F 'aquasec/trivy@sha256:' "$repo_root/scripts/scan-image" >/dev/null
grep -F 'vulnerabilities: []' "$repo_root/security/trivyignore.yaml" >/dev/null

# Keep the recurring rebuild and release evidence contracts explicit.
grep -F 'cron: "17 13 * * 1"' "$repo_root/.github/workflows/image_ci.yml" >/dev/null
grep -F "no-cache: \${{ github.event_name == 'schedule' }}" "$repo_root/.github/workflows/image_ci.yml" >/dev/null
grep -F 'scripts/scan-image tf-image-build:ci-' "$repo_root/.github/workflows/image_ci.yml" >/dev/null
grep -F 'scripts/scan-image tf-image-build:release-candidate-' "$repo_root/.github/workflows/release.yml" >/dev/null
grep -F 'retention-days: 90' "$repo_root/.github/workflows/release.yml" >/dev/null
grep -F 'sbom: true' "$repo_root/.github/workflows/release.yml" >/dev/null
grep -F 'provenance: mode=max' "$repo_root/.github/workflows/release.yml" >/dev/null

first_context_rule=$(grep -Ev '^[[:space:]]*(#|$)' "$repo_root/.dockerignore" | sed -n '1p')
if [ "$first_context_rule" != '*' ]; then
    echo '.dockerignore must exclude the context by default' >&2
    exit 1
fi
