#!/bin/sh

set -eu

endpoint=http://host.docker.internal:18080

if [ "${AWS_EC2_METADATA_SERVICE_ENDPOINT+x}" != x ] &&
    [ "${AWS_CONTAINER_CREDENTIALS_FULL_URI+x}" != x ] &&
    [ "${AWS_CONTAINER_CREDENTIALS_RELATIVE_URI+x}" != x ] &&
    curl --noproxy '*' --silent --fail \
        --request PUT \
        --header 'X-aws-ec2-metadata-token-ttl-seconds: 60' \
        --connect-timeout 1 --max-time 1 --output /dev/null \
        "${endpoint}/latest/api/token" 2>/dev/null; then
    export AWS_EC2_METADATA_SERVICE_ENDPOINT=$endpoint
fi

exec "$@"
